name: bus_tracker_app
description: KU Bus Tracking App

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  web_socket_channel: ^2.4.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  provider: ^6.0.5
  intl: ^0.18.1

flutter:
  uses-material-design: true